version: '3'
services:
  server:
    image: tokinring/alpine-arm
    stdin_open: true
    tty: true
    command: ["sh", "-c", "set -e; printf 'http://mirror.clarkson.edu/alpine/edge/testing\n' >> /etc/apk/repositories; apk update; apk --no-cache add deluge boost-python"]
